INSERT INTO users (userId, username, userPassword, email, addressId, [role])
VALUES 
(1, 'alice', 'password1', 'alice@example.com', 1, 'customer'),
(2, 'bob', 'password2', 'bob@example.com', 2, 'customer'),
(3, 'carol', 'password3', 'carol@example.com', 3, 'customer'),
(4, 'dave', 'password4', 'dave@example.com', 4, 'customer'),
(5, 'eve', 'password5', 'eve@example.com', 5, 'admin'),
(6, 'frank', 'password6', 'frank@example.com', 6, 'staff'),
(7, 'grace', 'password7', 'grace@example.com', 7, 'customer'),
(8, 'henry', 'password8', 'henry@example.com', 8, 'customer'),
(9, 'isabel', 'password9', 'isabel@example.com', 9, 'customer'),
(10, 'jack', 'password10', 'jack@example.com', 10, 'customer'),
(11, 'karen', 'password11', 'karen@example.com', 11, 'staff'),
(12, 'lucas', 'password12', 'lucas@example.com', 12, 'customer'),
(13, 'molly', 'password13', 'molly@example.com', 13, 'customer'),
(14, 'nathan', 'password14', 'nathan@example.com', 14, 'customer'),
(15, 'olivia', 'password15', 'olivia@example.com', 15, 'admin'),
(16, 'peter', 'password16', 'peter@example.com', 16, 'staff'),
(17, 'quinn', 'password17', 'quinn@example.com', 17, 'customer'),
(18, 'rachel', 'password18', 'rachel@example.com', 18, 'customer'),
(19, 'steve', 'password19', 'steve@example.com', 19, 'customer'),
(20, 'tina', 'password20', 'tina@example.com', 20, 'customer'),
(21, 'uwe', 'password21', 'uwe@example.com', 21, 'staff'),
(22, 'victor', 'password22', 'victor@example.com', 22, 'customer'),
(23, 'wendy', 'password23', 'wendy@example.com', 23, 'customer'),
(24, 'xavier', 'password24', 'xavier@example.com', 24, 'customer'),
(25, 'yvonne', 'password25', 'yvonne@example.com', 25, 'admin'),
(26, 'zack', 'password26', 'zack@example.com', 26, 'staff'),
(27, 'emma', 'password27', 'emma@example.com', 27, 'customer'),
(28, 'liam', 'password28', 'liam@example.com', 28, 'customer'),
(29, 'ava', 'password29', 'ava@example.com', 29, 'customer'),
(30, 'noah', 'password30', 'noah@example.com', 30, 'customer'),
(31, 'oliver', 'password31', 'oliver@example.com', 31, 'staff'),
(32, 'isla', 'password32', 'isla@example.com', 32, 'customer'),
(33, 'mia', 'password33', 'mia@example.com', 33, 'customer'),
(34, 'jacob', 'password34', 'jacob@example.com', 34, 'customer'),
(35, 'james', 'password35', 'james@example.com', 35, 'customer'),
(36, 'charlotte', 'password36', 'charlotte@example.com', 36, 'staff'),
(37, 'emily', 'password37', 'emily@example.com', 37, 'customer'),
(38, 'elijah', 'password38', 'elijah@example.com', 38, 'customer'),
(39, 'ethan', 'password39', 'ethan@example.com', 39, 'customer'),
(40, 'ava', 'password40', 'ava@example.com', 40, 'customer');


select * from users;